### ISSUE TITLE
does not work in Ruby 3.1.0  undefined method `encode' for URI:Module\e[0m (NoMethodError)

### ISSUE THREAD

**Issue by ccfiel** [shr3jn/fastlane-plugin-huawei_appgallery_connect#35]
```
gem/ruby/ruby/3.1.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.18/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:245:in `submit_app_for_review': \e[31m[!] undefined method `encode' for URI:Module\e[0m (NoMethodError)
```

URI.encode is now depreciated. How can we solve this issue?

**Comment by ccfiel** [comment]
@shr3jn I made a PR for this https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect/pull/37

**Comment by shr3jn** [comment]
released v1.0.19
